"""initial_schema

Revision ID: dfa36ee3884b
Revises: 
Create Date: 2026-06-08 20:27:29.444382

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa36ee3884b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_codes_code'), 'invite_codes', ['code'], unique=True)
    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_hash_name', sa.String(length=256), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshot_item_time', 'price_snapshots', ['market_hash_name', 'timestamp'], unique=False)
    op.create_index(op.f('ix_price_snapshots_market_hash_name'), 'price_snapshots', ['market_hash_name'], unique=False)
    op.create_index(op.f('ix_price_snapshots_timestamp'), 'price_snapshots', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('steam_id', sa.String(length=32), nullable=True),
    sa.Column('steam_api_key_encrypted', sa.String(length=512), nullable=True),
    sa.Column('server_chan_key_encrypted', sa.String(length=512), nullable=True),
    sa.Column('preferred_source', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alert_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('market_hash_name', sa.String(length=256), nullable=False),
    sa.Column('rule_type', sa.Integer(), nullable=False),
    sa.Column('old_price', sa.Float(), nullable=True),
    sa.Column('new_price', sa.Float(), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_logs_user_id'), 'alert_logs', ['user_id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=False),
    sa.Column('market_hash_name', sa.String(length=256), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('tradable', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_market_hash_name'), 'inventory_items', ['market_hash_name'], unique=False)
    op.create_index(op.f('ix_inventory_items_user_id'), 'inventory_items', ['user_id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('market_hash_name', sa.String(length=256), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('cost_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Integer(), nullable=False),
    sa.Column('threshold_pct', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_items_market_hash_name'), 'watchlist_items', ['market_hash_name'], unique=False)
    op.create_index(op.f('ix_watchlist_items_user_id'), 'watchlist_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_items_user_id'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_market_hash_name'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_inventory_items_user_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_market_hash_name'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_alert_logs_user_id'), table_name='alert_logs')
    op.drop_table('alert_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_price_snapshots_timestamp'), table_name='price_snapshots')
    op.drop_index(op.f('ix_price_snapshots_market_hash_name'), table_name='price_snapshots')
    op.drop_index('idx_snapshot_item_time', table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_index(op.f('ix_invite_codes_code'), table_name='invite_codes')
    op.drop_table('invite_codes')
    # ### end Alembic commands ###
